package com.t2.compassionMeditation;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.logger.Log;
import com.j256.ormlite.field.DataType;


public class BioUser  implements Serializable {

		private static final long serialVersionUID = -7874823823497497349L;
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;

	@DatabaseField(index = true)
	String name;

	@DatabaseField
	int minTheta;

	@DatabaseField
	int maxTheta;

	@DatabaseField
	int sessionCount;

	@DatabaseField
	Date createDate;

	@DatabaseField
	boolean even;
	
	
	@DatabaseField(dataType=DataType.SERIALIZABLE)
	Vector<Long> data;

	
//	@DatabaseField(dataType=DataType.SERIALIZABLE)
	List<SessionDataPoint> sessionDataPoints;;	
	

	//@DatabaseField
	//Vector data;

	BioUser() {
		// needed by ormlite
	}

	public BioUser(String name, long currentDate) {
		this.createDate = new Date(currentDate);
		this.name = name;
		this.data = new Vector();
		
		this.sessionDataPoints = new ArrayList<SessionDataPoint>();
//		List<SessionDataPoint> clickGroups = new ArrayList<SessionDataPoint>();	

		
		//		data.add(l);
//		data.add(l1);
//		data.add(new Long(millis + 2));
		
		
		
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("string=").append(name);
	//	sb.append(", ").append("millis=").append(millis);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
	//	sb.append(", ").append("date=").append(dateFormatter.format(date));
		sb.append(", ").append("even=").append(even);
		
		for(Long l: data) {
			sb.append(", ").append("l=").append(l);
			
		}
		return sb.toString();
	}
}
