package com.t2.compassionMeditation;

import java.io.Serializable;
import java.util.ArrayList;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;

public class SessionDataPoint  implements Serializable {
	private static final long serialVersionUID = -7874823823497497338L;
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;	
	
	@DatabaseField
	public long time;
	@DatabaseField
	private double valueSum = 0.00;
	@DatabaseField
	private int count = 0;
	@DatabaseField
	public double minValue = 0.00;
	@DatabaseField
	public double maxValue = 0.00;

	@DatabaseField(dataType=DataType.SERIALIZABLE)
	private ArrayList<Double> values = new ArrayList<Double>();
	
	@DatabaseField
	private double defaultValue = 0.00;
	
	public SessionDataPoint() {
		// needed by ormlite
	}
	
	public SessionDataPoint(long time, double defaultValue) {
		this.time = time;
		this.defaultValue = defaultValue;
	}
	
	public void addValue(double val) {
		values.add(val);
		valueSum += val;
		++count;
		
		if(val > maxValue || count == 1) {
			maxValue = val;
		}
		
		if(val < minValue || count == 1) {
			minValue = val;
		}
	}
	
	public double getAverageValue() {
		if(valueSum == 0 && count == 0) {
			return defaultValue;
		}
		return valueSum / count;
	}
	
	public double[] getValues() {
		double[] out = new double[values.size()];
		for(int i = 0; i < values.size(); ++i) {
			out[i] = values.get(i);
		}
		return out;
	}
}
