package com.t2.compassionDB;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;


//@DatabaseTable(tableName = "accounts")
@DatabaseTable
public class BioUser{

	public static final String NAME_FIELD_NAME = "name";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;

	@DatabaseField(columnName = NAME_FIELD_NAME, canBeNull = false)
	public String name;

	@DatabaseField
	int minTheta;

	@DatabaseField
	int maxTheta;

	@DatabaseField
	int sessionCount;

	@DatabaseField
	Date createDate;

	@DatabaseField
	boolean even;
	
	@ForeignCollectionField
	private ForeignCollection<BioSession> sessions;	
	

	BioUser() {
		// needed by ormlite
	}

	public BioUser(String name, long currentDate) {
		this.createDate = new Date(currentDate);
		this.name = name;
	}

	public ForeignCollection<BioSession> getSessions() {
		return sessions;
	}	
	
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("string=").append(name);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("even=").append(even);
		

		return sb.toString();
	}
}
